security:
    enable_authenticator_manager: true
    encoders:
        App\Entity\User:
            algorithm: auto
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            login_throttling: null
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                target: questions.homepage
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 
    access_control:
        - { path: ^/questions/create, roles: IS_AUTHENTICATED_FULLY, method: POST }
        - { path: '/comments/{id<\d+>}/vote/{direction<up|down>}', roles: IS_AUTHENTICATED_FULLY, method: POST }
